on:
  push:

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-PSU-200-LIL-2-1-minishell1-alexandre.garbe.git"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Push Epitech
          uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url:
              ${{ env.MIRROR_URL }}
            ssh_private_key:
              ${{ secrets.SSH_PRIVATE_KEY }}
